[package]
name = "systeroid-parser"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
regex = "1.5.4"
globwalk = "0.8.1"
thiserror = "1.0.29"
flate2 = "1.0.22"
