[package]
name = "kparams-parser"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
lazy-regex = "2.2.1"

[dependencies.kparams-core]
version = "0.1.0"
path = "../kparams-core"
