[package]
name = "systeroid"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
rayon = "1.5.1"
getopts = "0.2.21"

[dependencies.systeroid-parser]
version = "0.1.0"
path = "../systeroid-parser"

[dependencies.systeroid-core]
version = "0.1.0"
path = "../systeroid-core"
