[package]
name = "systeroid-tui"
version = "0.1.0"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
repository = "https://github.com/orhun/systeroid"
edition = "2021"

[features]
# clipboard support is enabled as default
default = ["clipboard"]
clipboard = ["copypasta-ext"]

[dependencies]
termion = "1.5.6"
unicode-width = "0.1.9"
thiserror = "1.0.30"
getopts = "0.2.21"
copypasta-ext = { version = "0.3.7", optional = true }
colorsys = "0.6.5"

[dependencies.systeroid-core]
version = "0.1.0"
path = "../systeroid-core"

[dependencies.tui]
version = "0.17.0"
default-features = false
features = ["termion"]
